-- IncomeTableDataSourceTest#testDelete 用テストデータ
-- 削除前データ：DELETE_FLG=FALSE
INSERT INTO INCOME_TABLE (USER_ID, TARGET_YEAR, TARGET_MONTH, INCOME_CODE, INCOME_KUBUN, INCOME_DETAIL_CONTEXT, INCOME_KINGAKU, DELETE_FLG)
VALUES ('TEST-USER-ID', '2025', '12', '01', '1', '削除対象詳細', 100000.00, FALSE);
