-- IncomeTableDataSourceTest#testUpdate 用テストデータ
-- 更新前データ：INCOME_KUBUN="1", INCOME_DETAIL_CONTEXT="更新前詳細", INCOME_KINGAKU=100000.00
INSERT INTO INCOME_TABLE (USER_ID, TARGET_YEAR, TARGET_MONTH, INCOME_CODE, INCOME_KUBUN, INCOME_DETAIL_CONTEXT, INCOME_KINGAKU, DELETE_FLG)
VALUES ('TEST-USER-ID', '2025', '12', '01', '1', '更新前詳細', 100000.00, FALSE);
