-- 買い物登録情報テーブル:SHOPPING_REGIST_TABLEにデータを追加します。
INSERT INTO SHOPPING_REGIST_TABLE (USER_ID, TARGET_YEAR, TARGET_MONTH, SHOPPING_REGIST_CODE, SHOP_KUBUN_CODE, SHOP_CODE, SHOPPING_DATE, SHOPPING_REMARKS, SHOPPING_FOOD_EXPENSES, SHOPPING_FOOD_TAX_EXPENSES, SHOPPING_FOODB_EXPENSES, SHOPPING_FOODB_TAX_EXPENSES, SHOPPING_FOODC_EXPENSES, SHOPPING_FOODC_TAX_EXPENSES, SHOPPING_DINE_OUT_EXPENSES, SHOPPING_DINE_OUT_TAX_EXPENSES, SHOPPING_CONSUMER_GOODS_EXPENSES, SHOPPING_CONSUMER_GOODS_TAX_EXPENSES, SHOPPING_CLOTHES_EXPENSES, SHOPPING_CLOTHES_TAX_EXPENSES, SHOPPING_WORK_EXPENSES, SHOPPING_WORK_TAX_EXPENSES, SHOPPING_HOUSE_EQUIPMENT_EXPENSES, SHOPPING_HOUSE_EQUIPMENT_TAX_EXPENSES, SHOPPING_COUPON_PRICE, TOTAL_PURCHASE_PRICE, TAX_TOTAL_PURCHASE_PRICE, SHOPPING_TOTAL_AMOUNT)
  VALUES (/*[# mb:p="dto.userId"]*/ 1 /*[/]*/, /*[# mb:p="dto.targetYear"]*/ 2 /*[/]*/, /*[# mb:p="dto.targetMonth"]*/ 3 /*[/]*/, /*[# mb:p="dto.shoppingRegistCode"]*/ 4 /*[/]*/,
          /*[# mb:p="dto.shopKubunCode"]*/ 5 /*[/]*/, /*[# mb:p="dto.shopCode"]*/ 6 /*[/]*/, /*[# mb:p="dto.shoppingDate"]*/ 7 /*[/]*/, /*[# mb:p="dto.shoppingRemarks"]*/ 8 /*[/]*/,
          /*[# mb:p="dto.shoppingFoodExpenses"]*/ 9 /*[/]*/, /*[# mb:p="dto.shoppingFoodTaxExpenses"]*/ 10 /*[/]*/, /*[# mb:p="dto.shoppingFoodBExpenses"]*/ 11 /*[/]*/, /*[# mb:p="dto.shoppingFoodBTaxExpenses"]*/ 12 /*[/]*/,
          /*[# mb:p="dto.shoppingFoodCExpenses"]*/ 13 /*[/]*/, /*[# mb:p="dto.shoppingFoodCTaxExpenses"]*/ 14 /*[/]*/, /*[# mb:p="dto.shoppingDineOutExpenses"]*/ 15 /*[/]*/, /*[# mb:p="dto.shoppingDineOutTaxExpenses"]*/ 16 /*[/]*/,
          /*[# mb:p="dto.shoppingConsumerGoodsExpenses"]*/ 17 /*[/]*/, /*[# mb:p="dto.shoppingConsumerGoodsTaxExpenses"]*/ 18 /*[/]*/, /*[# mb:p="dto.shoppingClothesExpenses"]*/ 19 /*[/]*/, /*[# mb:p="dto.shoppingClothesTaxExpenses"]*/ 20 /*[/]*/,
          /*[# mb:p="dto.shoppingWorkExpenses"]*/ 21 /*[/]*/, /*[# mb:p="dto.shoppingWorkTaxExpenses"]*/ 22 /*[/]*/, /*[# mb:p="dto.shoppingHouseEquipmentExpenses"]*/ 23 /*[/]*/, /*[# mb:p="dto.shoppingHouseEquipmentTaxExpenses"]*/ 24 /*[/]*/,
          /*[# mb:p="dto.shoppingCouponPrice"]*/ 25 /*[/]*/, /*[# mb:p="dto.totalPurchasePrice"]*/ 26 /*[/]*/,/*[# mb:p="dto.taxTotalPurchasePrice"]*/ 27 /*[/]*/, /*[# mb:p="dto.shoppingTotalAmount"]*/ 28 /*[/]*/
         )