-- ユーザID、対象年、対象月を条件に買い物登録情報テーブル:SHOPPING_REGIST_TABLEを参照します。
SELECT A.TARGET_YEAR, A.TARGET_MONTH, A.SHOPPING_REGIST_CODE, B.SHOP_NAME, A.SHOPPING_DATE, A.SHOPPING_FOOD_EXPENSES, A.SHOPPING_FOOD_TAX_EXPENSES, A.SHOPPING_FOODB_EXPENSES, A.SHOPPING_FOODB_TAX_EXPENSES,
       A.SHOPPING_FOODC_EXPENSES, A.SHOPPING_FOODC_TAX_EXPENSES, A.SHOPPING_DINE_OUT_EXPENSES, A.SHOPPING_DINE_OUT_TAX_EXPENSES, A.SHOPPING_CONSUMER_GOODS_EXPENSES, A.SHOPPING_CONSUMER_GOODS_TAX_EXPENSES,
       A.SHOPPING_CLOTHES_EXPENSES, A.SHOPPING_CLOTHES_TAX_EXPENSES, A.SHOPPING_WORK_EXPENSES, A.SHOPPING_WORK_TAX_EXPENSES, A.SHOPPING_HOUSE_EQUIPMENT_EXPENSES, A.SHOPPING_HOUSE_EQUIPMENT_TAX_EXPENSES,
       A.SHOPPING_COUPON_PRICE, A.SHOPPING_TOTAL_AMOUNT
  FROM SHOPPING_REGIST_TABLE AS A, SHOP_TABLE AS B
  WHERE A.USER_ID = /*[# mb:p="dto.userId"]*/ 1 /*[/]*/ AND A.TARGET_YEAR = /*[# mb:p="dto.targetYear"]*/ 2 /*[/]*/ AND A.TARGET_MONTH = /*[# mb:p="dto.targetMonth"]*/ 3 /*[/]*/
     AND A.USER_ID = B.USER_ID AND A.SHOP_CODE = B.SHOP_CODE
  ORDER BY A.SHOPPING_DATE
