-- 銀行口座テーブル:BANK_ACCOUNT_TABLEにユーザID:TESTUSER001のデータが0件となるデータを登録
INSERT INTO BANK_ACCOUNT_TABLE (USER_ID, BANK_ACCOUNT_CODE, BANK_NAME, BANK_ACCOUNT_MEMO, BANK_ACCOUNT_SORT, ENABLE_FLG) VALUES
  ('TESTUSER001-NotFound', '01', 'テスト銀行０１', null, '01', true);
