-- 支出金額テーブルと支出項目テーブルから年月を条件に支払項目ごとの支出を検索して返します。
SELECT A.TARGET_YEAR, A.TARGET_MONTH, A.SISYUTU_ITEM_CODE, B.SISYUTU_ITEM_NAME, B.SISYUTU_ITEM_LEVEL, A.SISYUTU_KINGAKU, A.SISYUTU_KINGAKU_B, A.SISYUTU_KINGAKU_C, A.SISYUTU_SIHARAI_DATE
FROM SISYUTU_KINGAKU_TABLE AS A, SISYUTU_ITEM_TABLE AS B
WHERE A.USER_ID =  /*[# mb:p="dto.userId"]*/ 1 /*[/]*/ AND A.TARGET_YEAR =  /*[# mb:p="dto.targetYear"]*/ 2 /*[/]*/ AND A.TARGET_MONTH =  /*[# mb:p="dto.targetMonth"]*/ 3 /*[/]*/ 
	AND A.USER_ID = B.USER_ID AND A.SISYUTU_ITEM_CODE = B.SISYUTU_ITEM_CODE AND B.ENABLE_UPDATE_FLG = FALSE
ORDER BY B.SISYUTU_ITEM_SORT
