-- イベントテーブル:EVENT_ITEM_TABLE、支出項目テーブル:SISYUTU_ITEM_TABLEから指定のユーザID、支出項目コードを条件にイベント情報を参照します。
SELECT A.EVENT_CODE, B.SISYUTU_ITEM_NAME, A.EVENT_NAME, A.EVENT_DETAIL_CONTEXT, A.EVENT_START_DATE, A.EVENT_END_DATE
  FROM EVENT_ITEM_TABLE AS A, SISYUTU_ITEM_TABLE AS B
  WHERE A.USER_ID = /*[# mb:p="dto.userId"]*/ 1 /*[/]*/ AND A.SISYUTU_ITEM_CODE = /*[# mb:p="dto.sisyutuItemCode"]*/ 2 /*[/]*/ AND A.EVENT_EXIT_FLG IS FALSE
    AND A.USER_ID = B.USER_ID AND A.SISYUTU_ITEM_CODE = B.SISYUTU_ITEM_CODE
