-- 支払方法テーブル:PAYMENT_METHOD_TABLEにユーザID:TESTUSER001のデータが0件となるデータを登録
INSERT INTO PAYMENT_METHOD_TABLE (USER_ID, PAYMENT_METHOD_CODE, PAYMENT_METHOD_NAME, PAYMENT_METHOD_KUBUN,
       BANK_ACCOUNT_CODE, CLOSING_DAY, PAYMENT_METHOD_SORT, ENABLE_FLG, ENABLE_UPDATE_FLG) VALUES
  ('TESTUSER001-NotFound', '001', '現金', '1', null, null, '001', true, true);
