-- FixedCostTableDataSourceTest#testDelete 用テストデータ
-- 削除前データ：
--   FIXED_COST_NAME="削除対象支払名", FIXED_COST_DETAIL_CONTEXT="削除対象詳細"
--   FIXED_COST_KUBUN="1", FIXED_COST_SHIHARAI_TUKI="40"
--   FIXED_COST_SHIHARAI_TUKI_OPTIONAL_CONTEXT="削除対象任意詳細"
--   FIXED_COST_SHIHARAI_DAY="15", SHIHARAI_KINGAKU=30000.00
--   SISYUTU_ITEM_CODE="0002" (論理削除後も変更されないことを確認する項目)
INSERT INTO FIXED_COST_TABLE (
    USER_ID, FIXED_COST_CODE, FIXED_COST_NAME, FIXED_COST_DETAIL_CONTEXT,
    SISYUTU_ITEM_CODE, FIXED_COST_KUBUN,
    FIXED_COST_SHIHARAI_TUKI, FIXED_COST_SHIHARAI_TUKI_OPTIONAL_CONTEXT,
    FIXED_COST_SHIHARAI_DAY, SHIHARAI_KINGAKU, DELETE_FLG)
VALUES (
    'TEST-USER-ID', '0001', '削除対象支払名', '削除対象詳細',
    '0002', '1',
    '40', '削除対象任意詳細',
    '15', 30000.00, FALSE);
