-- FixedCostTableDataSourceTest#testUpdate 用テストデータ
-- 更新前データ：
--   FIXED_COST_NAME="更新前支払名", FIXED_COST_DETAIL_CONTEXT="更新前詳細"
--   FIXED_COST_KUBUN="1", FIXED_COST_SHIHARAI_TUKI="00"
--   FIXED_COST_SHIHARAI_TUKI_OPTIONAL_CONTEXT=NULL, FIXED_COST_SHIHARAI_DAY="27"
--   SHIHARAI_KINGAKU=50000.00
--   SISYUTU_ITEM_CODE="0001" (更新されないことを確認する項目)
INSERT INTO FIXED_COST_TABLE (
    USER_ID, FIXED_COST_CODE, FIXED_COST_NAME, FIXED_COST_DETAIL_CONTEXT,
    SISYUTU_ITEM_CODE, FIXED_COST_KUBUN,
    FIXED_COST_SHIHARAI_TUKI, FIXED_COST_SHIHARAI_TUKI_OPTIONAL_CONTEXT,
    FIXED_COST_SHIHARAI_DAY, SHIHARAI_KINGAKU, DELETE_FLG)
VALUES (
    'TEST-USER-ID', '0001', '更新前支払名', '更新前詳細',
    '0001', '1',
    '00', NULL,
    '27', 50000.00, FALSE);
