-- ExpenditureTableDataSourceTest#testUpdate 用テストデータ
-- 更新前データ：
--   EXPENDITURE_NAME="更新前支出名", EXPENDITURE_KUBUN="1", EXPENDITURE_DETAIL_CONTEXT="更新前詳細"
--   SIHARAI_DATE=2025-12-01, EXPENDITURE_ESTIMATE_KINGAKU=50000.00, EXPENDITURE_KINGAKU=40000.00
--   SISYUTU_ITEM_CODE="0001", EVENT_CODE="0001" (更新されないことを確認する項目)
INSERT INTO EXPENDITURE_TABLE (
    USER_ID, TARGET_YEAR, TARGET_MONTH, EXPENDITURE_CODE,
    SISYUTU_ITEM_CODE, EVENT_CODE,
    EXPENDITURE_NAME, EXPENDITURE_KUBUN, EXPENDITURE_DETAIL_CONTEXT,
    SIHARAI_DATE, EXPENDITURE_ESTIMATE_KINGAKU, EXPENDITURE_KINGAKU, DELETE_FLG)
VALUES (
    'TEST-USER-ID', '2025', '12', '001',
    '0001', '0001',
    '更新前支出名', '1', '更新前詳細',
    '2025-12-01', 50000.00, 40000.00, FALSE);
