-- ExpenditureTableDataSourceTest#testDelete 用テストデータ
-- 削除前データ：DELETE_FLG=FALSE
INSERT INTO EXPENDITURE_TABLE (
    USER_ID, TARGET_YEAR, TARGET_MONTH, EXPENDITURE_CODE,
    SISYUTU_ITEM_CODE, EVENT_CODE,
    EXPENDITURE_NAME, EXPENDITURE_KUBUN, EXPENDITURE_DETAIL_CONTEXT,
    SIHARAI_DATE, EXPENDITURE_ESTIMATE_KINGAKU, EXPENDITURE_KINGAKU, DELETE_FLG)
VALUES (
    'TEST-USER-ID', '2025', '12', '001',
    '0001', '0001',
    '削除対象支出名', '1', '削除対象詳細',
    '2025-12-05', 50000.00, 40000.00, FALSE);
