-- 固定費テーブル:FIXED_COST_TABLE と支出項目テーブル:SISYUTU_ITEM_TABLE から
-- 指定ユーザIDの固定費情報を Level-1・Level-2 祖先コード込みで取得します。
-- B       ：固定費に直接紐付く支出項目（リーフ）
-- ANCLVL1 ：SORT前方一致(2桁)でBのLevel-1祖先を取得（自分自身を含む）
-- ANCLVL2 ：SORT前方一致(4桁)でBのLevel-2祖先を取得（Level-1項目の場合はnull）
SELECT A.FIXED_COST_CODE, A.FIXED_COST_NAME, A.FIXED_COST_DETAIL_CONTEXT,
       B.SISYUTU_ITEM_NAME,
       A.SISYUTU_ITEM_CODE,
       ANCLVL1.SISYUTU_ITEM_CODE AS LEVEL1_SISYUTU_ITEM_CODE,
       ANCLVL2.SISYUTU_ITEM_CODE AS LEVEL2_SISYUTU_ITEM_CODE,
       A.FIXED_COST_SHIHARAI_TUKI, A.FIXED_COST_SHIHARAI_TUKI_OPTIONAL_CONTEXT,
       A.FIXED_COST_SHIHARAI_DAY, A.SHIHARAI_KINGAKU
  FROM FIXED_COST_TABLE AS A
  JOIN SISYUTU_ITEM_TABLE AS B
    ON A.USER_ID = B.USER_ID AND A.SISYUTU_ITEM_CODE = B.SISYUTU_ITEM_CODE
  JOIN SISYUTU_ITEM_TABLE AS ANCLVL1
    ON A.USER_ID = ANCLVL1.USER_ID
   AND ANCLVL1.SISYUTU_ITEM_LEVEL = '1'
   AND SUBSTRING(B.SISYUTU_ITEM_SORT, 1, 2) = SUBSTRING(ANCLVL1.SISYUTU_ITEM_SORT, 1, 2)
  LEFT JOIN SISYUTU_ITEM_TABLE AS ANCLVL2
    ON A.USER_ID = ANCLVL2.USER_ID
   AND ANCLVL2.SISYUTU_ITEM_LEVEL = '2'
   AND SUBSTRING(B.SISYUTU_ITEM_SORT, 1, 4) = SUBSTRING(ANCLVL2.SISYUTU_ITEM_SORT, 1, 4)
 WHERE A.USER_ID = /*[# mb:p="dto.userId"]*/ 1 /*[/]*/ AND A.DELETE_FLG IS FALSE
 ORDER BY B.SISYUTU_ITEM_SORT, A.FIXED_COST_SHIHARAI_TUKI
