-- ユーザID,対象年度を条件に収支テーブルと支出金額テーブルを検索して返します。
-- 支出金額テーブルは指定の支出項目コード(支出項目テーブルのレベルが1に設定されている項目コード)の値を1レコードにして返します。
SELECT
 A.TARGET_MONTH,
 A.EXPENSE_KINGAKU,
 A.SYUUSI_KINGAKU,
 SUM(CASE WHEN B.SISYUTU_ITEM_CODE='0100000000' THEN B.SISYUTU_KINGAKU ELSE 0 END)AS JIGYOU_KEIHI_KINGAKU,
 SUM(CASE WHEN B.SISYUTU_ITEM_CODE='0200000000' THEN B.SISYUTU_KINGAKU ELSE 0 END) AS KOTEI_HIKAZEI_KINGAKU,
 SUM(CASE WHEN B.SISYUTU_ITEM_CODE='0300000000' THEN B.SISYUTU_KINGAKU ELSE 0 END) AS KOTEI_KAZEI_KINGAKU,
 SUM(CASE WHEN B.SISYUTU_ITEM_CODE='0400000000' THEN B.SISYUTU_KINGAKU ELSE 0 END) AS IRUI_JYUUKYO_SETUBI_KINGAKU,
 SUM(CASE WHEN B.SISYUTU_ITEM_CODE='0500000000' THEN B.SISYUTU_KINGAKU ELSE 0 END) AS INSYOKU_NITIYOUHIN_KINGAKU,
 SUM(CASE WHEN B.SISYUTU_ITEM_CODE='0600000000' THEN B.SISYUTU_KINGAKU ELSE 0 END) AS SYUMI_GOTAKU_KINGAKU,
 SUM(B.SISYUTU_KINGAKU_B) AS SISYUTU_KINGAKU_B
FROM INCOME_AND_EXPENSE_TABLE AS A, SISYUTU_KINGAKU_TABLE AS B
WHERE A.USER_ID = /*[# mb:p="dto.userId"]*/ 1 /*[/]*/ AND A.TARGET_YEAR = /*[# mb:p="dto.targetYear"]*/ 2 /*[/]*/ AND A.TARGET_MONTH = /*[# mb:p="dto.targetMonth"]*/ 3 /*[/]*/ 
 AND A.USER_ID = B.USER_ID AND A.TARGET_YEAR = B.TARGET_YEAR AND A.TARGET_MONTH = B.TARGET_MONTH AND A.TARGET_MONTH = B.TARGET_MONTH
 AND B.SISYUTU_ITEM_CODE IN ('0100000000', '0200000000', '0300000000', '0400000000', '0500000000', '0600000000')
ORDER BY A.TARGET_MONTH

