-- Spring Security users, authorities table
-- org/springframework/security/core/userdetails/jdbc/users.ddl
CREATE TABLE IF NOT EXISTS USERS(
	USERNAME VARCHAR(50) NOT NULL PRIMARY KEY,
	PASSWORD VARCHAR(500) NOT NULL,
	ENABLED BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS AUTHORITIES (
	USERNAME VARCHAR(50) NOT NULL,
	AUTHORITY VARCHAR(50) NOT NULL,
	CONSTRAINT FK_AUTHORITIES_USERS FOREIGN KEY(USERNAME) REFERENCES USERS(USERNAME)
);

-- 家計簿利用ユーザ:ACCOUNT_BOOK_USER ★本番テーブル定義登録済み★
-- DROP TABLE IF EXISTS ACCOUNT_BOOK_USER;
CREATE TABLE IF NOT EXISTS ACCOUNT_BOOK_USER (
	-- ユーザID
	USER_ID         VARCHAR(50),
	-- 現在の対象年
	NOW_TARGET_YEAR CHAR(4),
	-- 現在の対象月
	NOW_TARGET_MONTH     CHAR(2),
	-- ユーザ名
	USER_NAME       VARCHAR(100) NOT NULL,
	-- 複合プライマリキー
	PRIMARY KEY(USER_ID, NOW_TARGET_YEAR, NOW_TARGET_MONTH)
);


-- 支出項目テーブル:SISYUTU_ITEM_TABLE ★本番テーブル定義登録済み★
-- DROP TABLE IF EXISTS SISYUTU_ITEM_TABLE;
CREATE TABLE IF NOT EXISTS SISYUTU_ITEM_TABLE (
	-- ユーザID
	USER_ID         VARCHAR(50),
	-- 支出項目コード
	SISYUTU_ITEM_CODE    CHAR(4),
	-- 支出項目名
	SISYUTU_ITEM_NAME    VARCHAR(15)  NOT NULL,
	-- 支出項目詳細内容
	SISYUTU_ITEM_DETAIL_CONTEXT    VARCHAR(200),
	-- 親支出項目コード
	PARENT_SISYUTU_ITEM_CODE  CHAR(4)  NOT NULL,
	-- 支出項目レベル(1～5)
	SISYUTU_ITEM_LEVEL  CHAR(1) NOT NULL,
	-- 支出項目表示順
	SISYUTU_ITEM_SORT    CHAR(10) NOT NULL,
	-- 更新可否フラグ
	ENABLE_UPDATE_FLG    BOOLEAN NOT NULL,
	-- 複合プライマリキー
	PRIMARY KEY(USER_ID, SISYUTU_ITEM_CODE)
);


-- 支出項目テーブル(BASE):SISYUTU_ITEM_BASE_TABLE ★本番テーブル定義登録済み★
-- DROP TABLE IF EXISTS SISYUTU_ITEM_BASE_TABLE;
CREATE TABLE IF NOT EXISTS SISYUTU_ITEM_BASE_TABLE (
	-- 支出項目コード
	SISYUTU_ITEM_CODE    CHAR(4) PRIMARY KEY,
	-- 支出項目名
	SISYUTU_ITEM_NAME    VARCHAR(15)  NOT NULL,
	-- 支出項目詳細内容
	SISYUTU_ITEM_DETAIL_CONTEXT    VARCHAR(200),
	-- 親支出項目コード
	PARENT_SISYUTU_ITEM_CODE  CHAR(4)  NOT NULL,
	-- 支出項目レベル(1～5)
	SISYUTU_ITEM_LEVEL  CHAR(1) NOT NULL,
	-- 支出項目表示順
	SISYUTU_ITEM_SORT    CHAR(10) NOT NULL
);


-- 店舗テーブル:SHOP_TABLE ★本番テーブル定義登録済み★
-- DROP TABLE IF EXISTS SHOP_TABLE;
CREATE TABLE IF NOT EXISTS SHOP_TABLE (
	-- ユーザID
	USER_ID      VARCHAR(50),
	-- 店舗コード
	SHOP_CODE    CHAR(3),
	-- 店舗区分コード
	SHOP_KUBUN_CODE CHAR(3) NOT NULL,
	-- 店舗名
	SHOP_NAME    VARCHAR(50) NOT NULL,
	-- 店舗表示順
	SHOP_SORT    CHAR(3) NOT NULL,
	-- デフォルト支払方法コード(Feature1.03-dev1で追加。null可)
	DEFAULT_PAYMENT_METHOD_CODE CHAR(3),
	-- 複合プライマリキー
	PRIMARY KEY(USER_ID, SHOP_CODE)
);


-- 店舗テーブル(BASE):SHOP_BASE_TABLE ★本番テーブル定義登録済み★
-- DROP TABLE IF EXISTS SHOP_BASE_TABLE;
CREATE TABLE IF NOT EXISTS SHOP_BASE_TABLE (
	-- 店舗コード
	SHOP_CODE    CHAR(3) PRIMARY KEY,
	-- 店舗名
	SHOP_NAME    VARCHAR(50)  NOT NULL
);


-- 商品テーブル:SHOPPING_ITEM_TABLE ★本番テーブル定義登録済み★
-- DROP TABLE IF EXISTS SHOPPING_ITEM_TABLE;
CREATE TABLE IF NOT EXISTS SHOPPING_ITEM_TABLE (
	-- ユーザID
	USER_ID         VARCHAR(50),
	-- 商品コード
	SHOPPING_ITEM_CODE   CHAR(5),
	-- 商品区分名
	SHOPPING_ITEM_KUBUN_NAME  VARCHAR(30) NOT NULL,
	-- 商品名
	SHOPPING_ITEM_NAME   VARCHAR(100) NOT NULL,
	-- 商品詳細
	SHOPPING_ITEM_DETAIL_CONTEXT   VARCHAR(300),
	-- 商品JANコード(13桁 or 8桁 or ISBNコード:10桁)
	SHOPPING_ITEM_JAN_CODE    VARCHAR(13) NOT NULL,
	-- 支出項目コード(商品が属する支出項目コード)
	SISYUTU_ITEM_CODE    CHAR(4) NOT NULL,
	-- 会社名
	COMPANY_NAME    VARCHAR(100) NOT NULL,
	-- 基準店舗コード
	STANDARD_SHOP_CODE   CHAR(3),
	-- 基準価格
	STANDARD_PRICE  DECIMAL(8, 2),
	-- 内容量
	-- CAPACITY   SMALLINT UNSIGNED,
	CAPACITY   SMALLINT,
	-- 内容量単位
	CAPACITY_UNIT   CHAR(2),
	-- カロリー
	-- CALORIES   MEDIUMINT UNSIGNED,
	CALORIES   MEDIUMINT,
		
	-- 複合プライマリキー
	PRIMARY KEY(USER_ID, SHOPPING_ITEM_CODE),
	
	-- 外部キー:支出項目コード
	INDEX SHOPPING_ITEM_SISYUTU_ITEM_CODE_INDEX(SISYUTU_ITEM_CODE),
	CONSTRAINT FK_SHOPPING_ITEM_SISYUTU_ITEM_CODE FOREIGN KEY(USER_ID, SISYUTU_ITEM_CODE) REFERENCES SISYUTU_ITEM_TABLE(USER_ID, SISYUTU_ITEM_CODE)
);


-- 固定費テーブル:FIXED_COST_TABLE ★本番テーブル定義登録済み★
-- DROP TABLE IF EXISTS FIXED_COST_TABLE;
CREATE TABLE IF NOT EXISTS FIXED_COST_TABLE (
	-- ユーザID
	USER_ID         VARCHAR(50),
	-- 固定費コード
	FIXED_COST_CODE CHAR(4),
	-- 固定費名
	FIXED_COST_NAME VARCHAR(100) NOT NULL,
	-- 固定費内容詳細
	FIXED_COST_DETAIL_CONTEXT VARCHAR(300),
	-- 支出項目コード(固定費が属する支出項目コード)
	SISYUTU_ITEM_CODE    CHAR(4) NOT NULL,
	-- 固定費区分
	FIXED_COST_KUBUN     CHAR(1) NOT NULL,
	-- 固定費支払月
	FIXED_COST_SHIHARAI_TUKI  CHAR(2) NOT NULL,
	-- 固定費支払月任意詳細
	FIXED_COST_SHIHARAI_TUKI_OPTIONAL_CONTEXT     VARCHAR(300),
	-- 固定費支払日
	FIXED_COST_SHIHARAI_DAY   CHAR(2) NOT NULL,
	-- 支払金額
	SHIHARAI_KINGAKU     DECIMAL(8, 2) NOT NULL,
	-- 支払方法コード(Feature1.03-dev1で追加。テスト環境は本番データ移行と独立のため最初からNOT NULLで追加する)
	PAYMENT_METHOD_CODE  CHAR(3) NOT NULL,
	-- 削除フラグ
	DELETE_FLG BOOLEAN,

	-- 複合プライマリキー
	PRIMARY KEY(USER_ID, FIXED_COST_CODE),

	-- 外部キー:支出項目コード
	INDEX FIXED_COST_SISYUTU_ITEM_CODE_INDEX(SISYUTU_ITEM_CODE),
	CONSTRAINT FK_FIXED_COST_SISYUTU_ITEM_CODE FOREIGN KEY(USER_ID, SISYUTU_ITEM_CODE) REFERENCES SISYUTU_ITEM_TABLE(USER_ID, SISYUTU_ITEM_CODE)
);


-- イベントテーブル:EVENT_ITEM_TABLE ★本番テーブル定義登録済み★
-- DROP TABLE IF EXISTS EVENT_ITEM_TABLE;
CREATE TABLE IF NOT EXISTS EVENT_ITEM_TABLE (
	-- ユーザID
	USER_ID    VARCHAR(50),
	-- イベントコード
	EVENT_CODE CHAR(4),
	-- 支出項目コード(イベントが属する支出項目コード)
	SISYUTU_ITEM_CODE    CHAR(4) NOT NULL,
	-- イベント名
	EVENT_NAME VARCHAR(100) NOT NULL,
	-- イベント内容詳細
	EVENT_DETAIL_CONTEXT VARCHAR(300),
	-- イベント開始日
	EVENT_START_DATE     DATE NOT NULL,
	-- イベント終了日
	EVENT_END_DATE  DATE NOT NULL,
	-- 削除フラグ
	EVENT_EXIT_FLG  BOOLEAN NOT NULL,
	
	-- 複合プライマリキー
	PRIMARY KEY(USER_ID, EVENT_CODE)
);


-- ------------------------------------------------------------------------------------------
-- 収支関連
-- ------------------------------------------------------------------------------------------
-- 収支テーブル：INCOME_AND_EXPENDITURE_TABLE ★本番テーブル定義登録済み★
-- DROP TABLE IF EXISTS INCOME_AND_EXPENDITURE_TABLE;
CREATE TABLE IF NOT EXISTS INCOME_AND_EXPENDITURE_TABLE (
	-- ユーザID
	USER_ID         VARCHAR(50),
	-- 対象年
	TARGET_YEAR     CHAR(4),
	-- 対象月
	TARGET_MONTH    CHAR(2),
	-- 収入金額
	INCOME_KINGAKU  DECIMAL(12, 2) NOT NULL,
	-- 積立金取崩金額
	WITHDREW_KINGAKU     DECIMAL(12, 2),
	-- 支出予定金額
	EXPENDITURE_ESTIMATE_KINGAKU   DECIMAL(12, 2) NOT NULL,
	-- 支出金額
	EXPENDITURE_KINGAKU  DECIMAL(12, 2) NOT NULL,
	-- 収支金額
	INCOME_AND_EXPENDITURE_KINGAKU DECIMAL(12, 2) NOT NULL,
	
	-- ユニーク制約(各項目がNot Nullになっているのでプライマリキーと同じ Nullを許可したい場合のみ、ユニーク制約を使うのがいい)
	-- UNIQUE (USER_ID, TARGET_YEAR, TARGET_MONTH)
	-- 複合プライマリキー
	PRIMARY KEY(USER_ID, TARGET_YEAR, TARGET_MONTH)
);

-- ■　積立金取崩金額項目を収入金額項目の後に追加
-- ALTER TABLE INCOME_AND_EXPENDITURE_TABLE ADD WITHDREW_KINGAKU DECIMAL(12, 2) AFTER INCOME_KINGAKU;

-- 収支テーブルインデックス
-- 件数は1ユーザ年12件にしかならないので、このテーブルではインデックス不要(フルスキャンOK)


-- 支出金額テーブル：SISYUTU_KINGAKU_TABLE  ★本番テーブル定義登録済み★
-- DROP TABLE IF EXISTS SISYUTU_KINGAKU_TABLE;
CREATE TABLE IF NOT EXISTS SISYUTU_KINGAKU_TABLE (
	-- ユーザID
	USER_ID         VARCHAR(50),
	-- 対象年
	TARGET_YEAR     CHAR(4),
	-- 対象月
	TARGET_MONTH    CHAR(2),
	-- 支出項目コード
	SISYUTU_ITEM_CODE    CHAR(4),
	-- 親支出項目コード
	PARENT_SISYUTU_ITEM_CODE  CHAR(4)  NOT NULL,
	-- 支出予定金額
	SISYUTU_YOTEI_KINGAKU DECIMAL(12, 2) NOT NULL,
	-- 支出金額
	SISYUTU_KINGAKU DECIMAL(12, 2) NOT NULL,
	-- 支出金額B
	SISYUTU_KINGAKU_B    DECIMAL(12, 2),
	-- 支出金額C
	SISYUTU_KINGAKU_C    DECIMAL(12, 2),
	-- 支出支払日
	SISYUTU_SIHARAI_DATE DATE,
	
	-- 複合プライマリキー
	PRIMARY KEY(USER_ID, TARGET_YEAR, TARGET_MONTH, SISYUTU_ITEM_CODE),
	-- 外部キー:支出項目コード
	INDEX SISYUTU_ITEM_CODE_INDEX(SISYUTU_ITEM_CODE),
	CONSTRAINT FK_SISYUTU_ITEM_CODE FOREIGN KEY(USER_ID, SISYUTU_ITEM_CODE) REFERENCES SISYUTU_ITEM_TABLE(USER_ID, SISYUTU_ITEM_CODE)
);

-- 支出金額テーブルインデックス
-- CREATE INDEX SISYUTU_KINGAKU_TABLE_USER_YEAR ON SISYUTU_KINGAKU_TABLE (USER_ID, TARGET_YEAR);
-- CREATE INDEX SISYUTU_KINGAKU_TABLE_USER_YEAR_MONTH ON SISYUTU_KINGAKU_TABLE (USER_ID, TARGET_YEAR, TARGET_MONTH);


-- 支出テーブル：EXPENDITURE_TABLE  ★本番テーブル定義登録済み★
-- DROP TABLE IF EXISTS EXPENDITURE_TABLE;
CREATE TABLE IF NOT EXISTS EXPENDITURE_TABLE (
	-- ユーザID
	USER_ID         VARCHAR(50),
	-- 対象年
	TARGET_YEAR     CHAR(4),
	-- 対象月
	TARGET_MONTH    CHAR(2),
	-- 支出コード
	EXPENDITURE_CODE    CHAR(3),
	-- 支出項目コード
	SISYUTU_ITEM_CODE   CHAR(4) NOT NULL,
	-- イベントコード
	EVENT_CODE      CHAR(4),
	-- 支出名称
	EXPENDITURE_NAME     VARCHAR(100) NOT NULL,
	-- 支出区分
	EXPENDITURE_KUBUN    CHAR(1) NOT NULL,
	-- 支出詳細
	EXPENDITURE_DETAIL_CONTEXT     VARCHAR(300),
	-- 支払日
	SIHARAI_DATE    DATE,
	-- 支出予定金額
	EXPENDITURE_ESTIMATE_KINGAKU   DECIMAL(12, 2) NOT NULL,
	-- 支出金額
	EXPENDITURE_KINGAKU  DECIMAL(12, 2) NOT NULL,
	-- 支払方法コード(Feature1.03-dev1で追加。テスト環境は本番データ移行と独立のため最初からNOT NULLで追加する)
	PAYMENT_METHOD_CODE  CHAR(3) NOT NULL,
	-- 削除フラグ
	DELETE_FLG      BOOLEAN,

	-- 複合プライマリキー
	PRIMARY KEY(USER_ID, TARGET_YEAR, TARGET_MONTH, EXPENDITURE_CODE),

	-- 外部キー:支出項目コード
	INDEX EXPENDITURE_SISYUTU_ITEM_CODE_INDEX(SISYUTU_ITEM_CODE),
	CONSTRAINT FK_EXPENDITURE_SISYUTU_ITEM_CODE FOREIGN KEY(USER_ID, SISYUTU_ITEM_CODE) REFERENCES SISYUTU_ITEM_TABLE(USER_ID, SISYUTU_ITEM_CODE)
);


-- 収入テーブル：INCOME_TABLE  ★本番テーブル定義登録済み★
-- DROP TABLE IF EXISTS INCOME_TABLE;
CREATE TABLE IF NOT EXISTS INCOME_TABLE (
	-- ユーザID
	USER_ID         VARCHAR(50),
	-- 対象年
	TARGET_YEAR     CHAR(4),
	-- 対象月
	TARGET_MONTH    CHAR(2),
	-- 収入コード
	INCOME_CODE     CHAR(2),
	-- 収入区分
	INCOME_KUBUN    CHAR(1) NOT NULL,
	-- 収入詳細
	INCOME_DETAIL_CONTEXT     VARCHAR(300),
	-- 収入金額
	INCOME_KINGAKU DECIMAL(12, 2)  NOT NULL,
	-- 削除フラグ
	DELETE_FLG      BOOLEAN,
	
	-- 複合プライマリキー
	PRIMARY KEY(USER_ID, TARGET_YEAR, TARGET_MONTH, INCOME_CODE)
	
);

-- ------------------------------------------------------------------------------------------
-- 買い物登録関連
-- ------------------------------------------------------------------------------------------
-- 買い物登録情報テーブル：SHOPPING_REGIST_TABLE  ★本番テーブル定義登録済み★
-- DROP TABLE IF EXISTS SHOPPING_REGIST_TABLE;
CREATE TABLE IF NOT EXISTS SHOPPING_REGIST_TABLE (
	-- ユーザID
	USER_ID         VARCHAR(50),
	-- 対象年
	TARGET_YEAR     CHAR(4),
	-- 対象月
	TARGET_MONTH    CHAR(2),
	-- 買い物登録コード
	SHOPPING_REGIST_CODE     CHAR(3),
	-- 店舗区分コード
	SHOP_KUBUN_CODE CHAR(3) NOT NULL,
	-- 店舗コード
	SHOP_CODE    CHAR(3) NOT NULL,
	-- 買い物日
	SHOPPING_DATE    DATE NOT NULL,
	-- 備考
	SHOPPING_REMARKS     VARCHAR(150),
	-- 支払方法コード(Feature1.03-dev1で追加。テスト環境は本番データ移行と独立のため最初からNOT NULLで追加する)
	PAYMENT_METHOD_CODE  CHAR(3) NOT NULL,
	-- 食料品(必須)金額
	SHOPPING_FOOD_EXPENSES DECIMAL(8, 2),
	-- 消費税:食料品(必須)金額
	SHOPPING_FOOD_TAX_EXPENSES DECIMAL(8, 2),
	-- 食料品B(無駄遣い)金額
	SHOPPING_FOODB_EXPENSES DECIMAL(8, 2),
	-- 消費税:食料品B(無駄遣い)金額
	SHOPPING_FOODB_TAX_EXPENSES DECIMAL(8, 2),
	-- 食料品C(お酒類)金額
	SHOPPING_FOODC_EXPENSES DECIMAL(8, 2),
	-- 消費税:食料品C(お酒類)金額
	SHOPPING_FOODC_TAX_EXPENSES DECIMAL(8, 2),
	-- 外食金額
	SHOPPING_DINE_OUT_EXPENSES DECIMAL(8, 2),
	-- 消費税:外食金額
	SHOPPING_DINE_OUT_TAX_EXPENSES DECIMAL(8, 2),
	-- 日用品金額
	SHOPPING_CONSUMER_GOODS_EXPENSES DECIMAL(8, 2),
	-- 消費税:日用品金額
	SHOPPING_CONSUMER_GOODS_TAX_EXPENSES DECIMAL(8, 2),
	-- 衣料品(私服)金額
	SHOPPING_CLOTHES_EXPENSES DECIMAL(8, 2),
	-- 消費税:衣料品(私服)金額
	SHOPPING_CLOTHES_TAX_EXPENSES DECIMAL(8, 2),
	-- 仕事金額
	SHOPPING_WORK_EXPENSES DECIMAL(9, 2),
	-- 消費税:仕事金額
	SHOPPING_WORK_TAX_EXPENSES DECIMAL(9, 2),
	-- 住居設備金額
	SHOPPING_HOUSE_EQUIPMENT_EXPENSES DECIMAL(9, 2),
	-- 消費税:住居設備金額
	SHOPPING_HOUSE_EQUIPMENT_TAX_EXPENSES DECIMAL(9, 2),
	-- クーポン
	SHOPPING_COUPON_PRICE DECIMAL(8, 2),
	-- 購入金額合計
	TOTAL_PURCHASE_PRICE DECIMAL(12, 2) NOT NULL,
	-- 消費税合計
	TAX_TOTAL_PURCHASE_PRICE DECIMAL(12, 2),
	-- 買い物合計金額
	SHOPPING_TOTAL_AMOUNT DECIMAL(12, 2) NOT NULL,
	
	-- 複合プライマリキー
	PRIMARY KEY(USER_ID, TARGET_YEAR, TARGET_MONTH, SHOPPING_REGIST_CODE)

);

-- ------------------------------------------------------------------------------------------
-- 支払方法・銀行口座管理関連(Feature1.03-dev1)
-- ------------------------------------------------------------------------------------------
-- 銀行口座テーブル：BANK_ACCOUNT_TABLE
-- DROP TABLE IF EXISTS BANK_ACCOUNT_TABLE;
CREATE TABLE IF NOT EXISTS BANK_ACCOUNT_TABLE (
	-- ユーザID
	USER_ID              VARCHAR(50),
	-- 銀行口座コード
	BANK_ACCOUNT_CODE    CHAR(2),
	-- 銀行名
	BANK_NAME             VARCHAR(50) NOT NULL,
	-- 口座メモ(口座のエイリアス)
	BANK_ACCOUNT_MEMO     VARCHAR(100),
	-- 銀行口座表示順
	BANK_ACCOUNT_SORT     CHAR(2) NOT NULL,
	-- 有効/無効フラグ(trueの時は有効、falseの時は無効)
	ENABLE_FLG            BOOLEAN NOT NULL,

	-- 複合プライマリキー
	PRIMARY KEY(USER_ID, BANK_ACCOUNT_CODE)
);

-- 支払方法テーブル：PAYMENT_METHOD_TABLE
-- DROP TABLE IF EXISTS PAYMENT_METHOD_TABLE;
CREATE TABLE IF NOT EXISTS PAYMENT_METHOD_TABLE (
	-- ユーザID
	USER_ID                  VARCHAR(50),
	-- 支払方法コード
	PAYMENT_METHOD_CODE      CHAR(3),
	-- 支払方法名
	PAYMENT_METHOD_NAME      VARCHAR(50) NOT NULL,
	-- 支払方法メモ(dev2のクレジットカードポイント減算で、設定値がある場合のみ画面表示)
	PAYMENT_METHOD_MEMO      VARCHAR(400),
	-- 支払方法種別(1:現金 2:口座振替 3:クレジットカード 4:デビットカード 5:電子マネー(前払い式))
	PAYMENT_METHOD_KUBUN     CHAR(1) NOT NULL,
	-- 銀行口座コード(種別により要否が異なる。口座振替/クレジットカード/デビットカードは必須、現金/電子マネー(前払い式)はNULL可)
	BANK_ACCOUNT_CODE        CHAR(2),
	-- 集計開始日(クレジットカードのみ。1～28)
	CLOSING_DAY              CHAR(2),
	-- 支払方法表示順
	PAYMENT_METHOD_SORT      CHAR(3) NOT NULL,
	-- 有効/無効フラグ(trueの時は有効、falseの時は無効)
	ENABLE_FLG               BOOLEAN NOT NULL,
	-- 更新可否フラグ(trueの時は更新可能、falseの時は更新不可。「支払方法がない」システム行はfalse)
	ENABLE_UPDATE_FLG        BOOLEAN NOT NULL,

	-- 複合プライマリキー
	PRIMARY KEY(USER_ID, PAYMENT_METHOD_CODE),

	-- 外部キー:銀行口座コード(NULL可のFK。値がある場合のみ整合性を検証)
	INDEX PAYMENT_METHOD_BANK_ACCOUNT_CODE_INDEX(BANK_ACCOUNT_CODE),
	CONSTRAINT FK_PAYMENT_METHOD_BANK_ACCOUNT_CODE FOREIGN KEY(USER_ID, BANK_ACCOUNT_CODE) REFERENCES BANK_ACCOUNT_TABLE(USER_ID, BANK_ACCOUNT_CODE)
);

-- SHOP_TABLE.DEFAULT_PAYMENT_METHOD_CODE の外部キー(PAYMENT_METHOD_TABLE作成後でないと追加できないためALTERで付与)
-- IF NOT EXISTSを付与し、テスト実行中にSpringが複数回ApplicationContextを構築して本スクリプトが再実行されても
-- エラーにならないようにする(H2はIF NOT EXISTSに対応。MariaDBは10.5.2+で対応、それ未満の場合は一度だけ適用しコメントアウトすること)
ALTER TABLE SHOP_TABLE ADD CONSTRAINT IF NOT EXISTS FK_SHOP_DEFAULT_PAYMENT_METHOD_CODE
	FOREIGN KEY(USER_ID, DEFAULT_PAYMENT_METHOD_CODE) REFERENCES PAYMENT_METHOD_TABLE(USER_ID, PAYMENT_METHOD_CODE);

-- FIXED_COST_TABLE/EXPENDITURE_TABLE/SHOPPING_REGIST_TABLE の PAYMENT_METHOD_CODE への外部キー付与は、
-- 各テーブルの全既存テストフィクスチャにPAYMENT_METHOD_TABLEの対応行を用意する回収作業を伴うため、
-- 8章確認事項④の回答で明示的に前倒しが確認されている「NOT NULL化」のみ先に実施し、FK制約は見送る。

